In [127]:
import numpy as np
import pycosat
import itertools

In [103]:
def initialize(n):
    names = np.zeros([n,2*n,2*n],dtype=np.int)
    for i in range(n):
        for j in range(2*n):
            for k in range(2*n):
                names[i][j][k]= i*(2*n)**2 + j*2*n + k+1
    return names.tolist()

def encode_at_most_one(cnf, names, show):
    if show:
        print("enter function encode_at_most_one")
    n = len(names)
    #enc = []
    for i in range(n):
        for j in range(2*n):
            if show:
                print("in row ", i, ", column", j, ", there may only be at most 1 number, hence the following clauses:")
            for k in range(2*n):
                for l in range(1,(2*n)-k):
                    arr = [-1*names[i][j][k],-1*names[i][j][k+l]]
                    if show:
                        print(arr)
                    per_entry = cnf.insert(0,arr)
    return cnf

def encode_at_least_one(cnf,names,show):
    if show:
        print("enter function encode_at_least_one")
        print("for every field we expect a clause of", len(names[0]), "positive literals:")
    for i in names:
        atleast=[]
        for j in i:
            atleast.append(j)
            if show:
                print(j)
        cnf.extend(atleast)
    return cnf
    
def encode_exactly_one(cnf, names, show):
    if show:
        print("enter function encode_exactly_one")
    full = []
    full.extend(encode_at_most_one(cnf, names, show))
    full.extend(encode_at_least_one(cnf, names, show))
    return full



def encode_doku_as_cnf(names, show):
    cnf = []
    encode_exactly_one(cnf, names, show)
    if show:
        print("the doku is now translated to propositional logic in cnf format")
    return cnf

In [4]:
##### EXAMPLE
doku = initialize(2)
example = encode_doku_as_cnf(doku, True)
print( example )
pycosat.solve(example)

enter function encode_exactly_one
enter function encode_at_most_one
in row  0 , column 0 , there may only be at most 1 number, hence the following clauses:
[-1, -2]
[-1, -3]
[-1, -4]
[-2, -3]
[-2, -4]
[-3, -4]
in row  0 , column 1 , there may only be at most 1 number, hence the following clauses:
[-5, -6]
[-5, -7]
[-5, -8]
[-6, -7]
[-6, -8]
[-7, -8]
in row  0 , column 2 , there may only be at most 1 number, hence the following clauses:
[-9, -10]
[-9, -11]
[-9, -12]
[-10, -11]
[-10, -12]
[-11, -12]
in row  0 , column 3 , there may only be at most 1 number, hence the following clauses:
[-13, -14]
[-13, -15]
[-13, -16]
[-14, -15]
[-14, -16]
[-15, -16]
in row  1 , column 0 , there may only be at most 1 number, hence the following clauses:
[-17, -18]
[-17, -19]
[-17, -20]
[-18, -19]
[-18, -20]
[-19, -20]
in row  1 , column 1 , there may only be at most 1 number, hence the following clauses:
[-21, -22]
[-21, -23]
[-21, -24]
[-22, -23]
[-22, -24]
[-23, -24]
in row  1 , column 2 , there may on

[-1,
 -2,
 -3,
 4,
 -5,
 -6,
 -7,
 8,
 -9,
 -10,
 -11,
 12,
 -13,
 -14,
 -15,
 16,
 -17,
 -18,
 -19,
 20,
 -21,
 -22,
 -23,
 24,
 -25,
 -26,
 -27,
 28,
 -29,
 -30,
 -31,
 32]

In [46]:
a = initialize(2)

a=np.array(a)

a[:,::2].tolist()
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]


In [158]:
def getslice(k,names):
    cnf = []
    slice_C = []
    n = len(names)
    for i in range(n):
        for j in range(k,2*n,n):
            a = names[i][j]
            slice_C.append(a)
            
    return slice_C

def slice_cnf(names):
    cnf = []
    for i in range(n):
        sliced = getslice(i,names)
        atleast_n =[]
        comb_n = []
        for l in range(2*n):
            atleast= [k[l] for k in sliced]
            atleast_n.append(atleast)
            atleast_neg = [-x for x in atleast]
            comb = [list(z) for z in itertools.combinations(atleast_neg,n)]
            
           
            atleast_n.append(comb)
        cnf.append(atleast_n)
        #cnf.append(comb_n)
    return cnf