In [22]:
import numpy as np
import pycosat
import itertools

In [36]:
def initialize(n):
    names = np.zeros([n,2*n,2*n],dtype=np.int)
    for i in range(n):
        for j in range(2*n):
            for k in range(2*n):
                names[i][j][k]= i*(2*n)**2 + j*2*n + k+1
    return names.tolist()

def encode_at_most_one(cnf, names, show):
    if show:
        print("enter function encode_at_most_one")
    n = len(names)
    #enc = []
    for i in range(n):
        for j in range(2*n):
            if show:
                print("in row ", i, ", column", j, ", there may only be at most 1 number, hence the following clauses:")
            for k in range(2*n):
                for l in range(1,(2*n)-k):
                    arr = [-1*names[i][j][k],-1*names[i][j][k+l]]
                    if show:
                        print(arr)
                    per_entry = cnf.insert(0,arr)
    return cnf

def encode_at_least_one(cnf,names,show):
    if show:
        print("enter function encode_at_least_one")
        print("for every field we expect a clause of", len(names[0]), "positive literals:")
    for i in names:
        atleast=[]
        for j in i:
            atleast.append(j)
            if show:
                print(j)
        cnf.extend(atleast)
    return cnf
    
def encode_exactly_one(cnf, names, show):
    if show:
        print("enter function encode_exactly_one")
    
    cnf.extend(encode_at_most_one(cnf, names, show))
    cnf.extend(encode_at_least_one(cnf, names, show))
    return cnf





In [17]:
##### EXAMPLE
doku = initialize(2)
example = encode_doku_as_cnf(doku, True)
print( example )
pycosat.solve(example)

TypeError: encode_doku_as_cnf() missing 1 required positional argument: 'doku'

In [ ]:
a = initialize(2)

a=np.array(a)

a[:,::2].tolist()
print(a)

In [ ]:
def getslice(k,names):
    
    slice_C = []
    n = len(names)
    for i in range(n):
        for j in range(k,2*n,n):
            a = names[i][j]
            slice_C.append(a)
            
    return slice_C

def slice_cnf(cnf, names):
    n = len(names)

    for i in range(n):
        sliced = getslice(i,names)
        atleast_n =[]
        comb_n = []
        for l in range(2*n):
            atleast= [k[l] for k in sliced]
            atleast_n.append(atleast)
            atleast_neg = [-x for x in atleast]
            comb = [list(z) for z in itertools.combinations(atleast_neg,n)]
            
           
            atleast_n.extend(comb)
        cnf.extend(atleast_n)
        
    return cnf

In [23]:
cnf = []
encode_ring(cnf,initialize(2),True)


enter encode_ring function

in row  0 , there may not be more than one 1
[-1, -5]
[-1, -9]
[-1, -13]
[-5, -9]
[-5, -13]
[-9, -13]
but there must be at least one  1
[1, 5, 9, 13]
in row  0 , there may not be more than one 2
[-2, -6]
[-2, -10]
[-2, -14]
[-6, -10]
[-6, -14]
[-10, -14]
but there must be at least one  2
[2, 6, 10, 14]
in row  0 , there may not be more than one 3
[-3, -7]
[-3, -11]
[-3, -15]
[-7, -11]
[-7, -15]
[-11, -15]
but there must be at least one  3
[3, 7, 11, 15]
in row  0 , there may not be more than one 4
[-4, -8]
[-4, -12]
[-4, -16]
[-8, -12]
[-8, -16]
[-12, -16]
but there must be at least one  4
[4, 8, 12, 16]
in row  1 , there may not be more than one 1
[-17, -21]
[-17, -25]
[-17, -29]
[-21, -25]
[-21, -29]
[-25, -29]
but there must be at least one  1
[17, 21, 25, 29]
in row  1 , there may not be more than one 2
[-18, -22]
[-18, -26]
[-18, -30]
[-22, -26]
[-22, -30]
[-26, -30]
but there must be at least one  2
[18, 22, 26, 30]
in row  1 , there may not be more t

[[-1, -5],
 [-1, -9],
 [-1, -13],
 [-5, -9],
 [-5, -13],
 [-9, -13],
 [1, 5, 9, 13],
 [-2, -6],
 [-2, -10],
 [-2, -14],
 [-6, -10],
 [-6, -14],
 [-10, -14],
 [2, 6, 10, 14],
 [-3, -7],
 [-3, -11],
 [-3, -15],
 [-7, -11],
 [-7, -15],
 [-11, -15],
 [3, 7, 11, 15],
 [-4, -8],
 [-4, -12],
 [-4, -16],
 [-8, -12],
 [-8, -16],
 [-12, -16],
 [4, 8, 12, 16],
 [-17, -21],
 [-17, -25],
 [-17, -29],
 [-21, -25],
 [-21, -29],
 [-25, -29],
 [17, 21, 25, 29],
 [-18, -22],
 [-18, -26],
 [-18, -30],
 [-22, -26],
 [-22, -30],
 [-26, -30],
 [18, 22, 26, 30],
 [-19, -23],
 [-19, -27],
 [-19, -31],
 [-23, -27],
 [-23, -31],
 [-27, -31],
 [19, 23, 27, 31],
 [-20, -24],
 [-20, -28],
 [-20, -32],
 [-24, -28],
 [-24, -32],
 [-28, -32],
 [20, 24, 28, 32]]

In [48]:
def encode_ring(cnf, names, show):
    if show:
        print("")
        print("enter encode_ring function")
        print("")
    n = len(names)
    for i in range(n):
        for k in range(2*n):
            at_least_clause = []
            if show:
                print("in row ", i, ", there may not be more than one", k+1)
            for j in range(2*n): 
                at_least_clause.append(names[i][j][k])
                at_most_clause = []
                for l in range(1,(2*n)-j):
                    at_most_clause = [-1*names[i][j][k], -1*names[i][j+l][k]]
                    cnf.extend([at_most_clause])
                    if show:
                        print(at_most_clause)
            cnf.extend([at_least_clause])
            if show:
                print("but there must be at least one ", k+1)
                print(at_least_clause)                
    return cnf

def encode_wedge(cnf, names, show):
    if show:
        print("")
        print("enter encode_wedge function")
        print("")
    n = len(names) # n is number of rings, but also number of wedges
    # first, collect all the variables that stand for a number "1" (or"k") in a wedge
    # then, construct clauses that say one of these variables must be true
    # but no more than one of thesevariables may be true
    for w in range(n): # per wedge
        for k in range(2*n): # per number
            wedge_content = []
            for i in range(n): # per row
                for j in range(2*w, 2*w+2): # per column
                    wedge_content.append(names[i][j][k])
            cnf.extend([wedge_content])
            if show:
                print("in wedge ", w, "there must be the number", k+1)
                print(wedge_content)
                print("but only one ", k+1)
            for l in range(2*n): # loop over the wedgecontent
                for m in range(1, 2*n - l):
                    clause = [-1*wedge_content[l], -1*wedge_content[l+m]]
                    if show:
                        print(clause)
    return cnf

def encode_givens(cnf, names, puzzle, show):
    n = len(names)
    for i in range(n):
        for j in range(2*n):
            for k in range(2*n):
                if puzzle[i,j] == k+1:
                    clause = [names[i][j][k]]
                    cnf.extend([clause])
                    if show:
                        print("givens-clause: ", clause)
    return cnf                   

In [21]:
a = np.loadtxt('valid_circledoku_2_rings_#0', delimiter=',', dtype='int' )

def reduce_CircleDoku(doku_puzzle):
    # this function takes a full, valid circledoku as input
    # and gives a proper circledoku with as few given as possible as output
    n = len(doku_puzzle)
    doku_indices = []
    for i in range(n):
        for j in range(2*n):
            doku_indices.append([i,j,doku_puzzle[i,j]])
    random.shuffle(doku_indices, random.random)
    print(doku_indices)
    
def indices_to_puzzle(doku_indices):
    n = len(doku_indices)/4
    doku_puzzle = np.zeros([n, 2*n], dtype=np.int)
    doku_puzzle.tolist()
    for i in range(len(doku_indices)):
        x = doku_indices[i][0]
        y = doku_indices[i][1]
        doku_puzzle[x][y] = doku_indices[i][2]
    return doku_puzzle
    
print(a)
reduce_CircleDoku(a)
encode_ring

[[2 1 3 4]
 [4 3 1 2]]


NameError: name 'random' is not defined

In [ ]:
def encode_doku_as_cnf(names, show, doku):
    cnf = []
    cnf = encode_exactly_one(cnf, names, show)
    cnf = encode_ring(cnf,names,show)
    cnf = encode_wedge(cnf,names,show)
    cnf = slice_cnf(cnf,names)
    cnf = encode_givens(cnf,names,doku,show)

    if show:
        print("the doku is now translated to propositional logic in cnf format")
        
    
    return cnf

In [49]:
a = np.loadtxt('valid_circledoku_2_rings_#0', delimiter=',', dtype='int' )
n = len(a)
a[0,0]=0
names = initialize(n)
cnf = encode_doku_as_cnf(names, False, a)
cnf

[[-31, -32],
 [-30, -32],
 [-30, -31],
 [-29, -32],
 [-29, -31],
 [-29, -30],
 [-27, -28],
 [-26, -28],
 [-26, -27],
 [-25, -28],
 [-25, -27],
 [-25, -26],
 [-23, -24],
 [-22, -24],
 [-22, -23],
 [-21, -24],
 [-21, -23],
 [-21, -22],
 [-19, -20],
 [-18, -20],
 [-18, -19],
 [-17, -20],
 [-17, -19],
 [-17, -18],
 [-15, -16],
 [-14, -16],
 [-14, -15],
 [-13, -16],
 [-13, -15],
 [-13, -14],
 [-11, -12],
 [-10, -12],
 [-10, -11],
 [-9, -12],
 [-9, -11],
 [-9, -10],
 [-7, -8],
 [-6, -8],
 [-6, -7],
 [-5, -8],
 [-5, -7],
 [-5, -6],
 [-3, -4],
 [-2, -4],
 [-2, -3],
 [-1, -4],
 [-1, -3],
 [-1, -2],
 [-31, -32],
 [-30, -32],
 [-30, -31],
 [-29, -32],
 [-29, -31],
 [-29, -30],
 [-27, -28],
 [-26, -28],
 [-26, -27],
 [-25, -28],
 [-25, -27],
 [-25, -26],
 [-23, -24],
 [-22, -24],
 [-22, -23],
 [-21, -24],
 [-21, -23],
 [-21, -22],
 [-19, -20],
 [-18, -20],
 [-18, -19],
 [-17, -20],
 [-17, -19],
 [-17, -18],
 [-15, -16],
 [-14, -16],
 [-14, -15],
 [-13, -16],
 [-13, -15],
 [-13, -14],
 [-11, -12],


In [50]:
print(a)
pycosat.solve(cnf)


[[0 1 3 4]
 [4 3 1 2]]


[-1,
 2,
 -3,
 -4,
 5,
 -6,
 -7,
 -8,
 -9,
 -10,
 11,
 -12,
 -13,
 -14,
 -15,
 16,
 -17,
 -18,
 -19,
 20,
 -21,
 -22,
 23,
 -24,
 25,
 -26,
 -27,
 -28,
 -29,
 30,
 -31,
 -32]