In [3]:
import numpy as np
import pycosat
import time

In [4]:
# this cell is responsible for generating valid filled circledokus

# for a circledoku of 3 rings we represent in an array as follows
#
# ring:
# [[1 1 1 1 1 1]
#  [0 0 0 0 0 0]
#  [0 0 0 0 0 0]]
#
# slice:
# [[1 0 0 1 0 0]
#  [1 0 0 1 0 0]
#  [1 0 0 1 0 0]]
#
# wedge:
# [[1 1 0 0 0 0]
#  [1 1 0 0 0 0]
#  [1 1 0 0 0 0]]

def gen_full_circledoku(n): # a circledoku with n-rings
    # this function fills a circledoku with a valid configuration
    # it is later filtered to become a unique proper puzzle with minimal givens, outside of this cell
    succes = False
    n_attempt = 0
    while not succes: 
        # if the computer runs into a dead-end by random assignment, just stop and start over
        # this is very inefficient especially for larger circledoku's
        # but in this generation step we are not troubled by efficiency
        succes, doku = attempt_full_circledoku(n)
#         past_attempt.append(doku)
        n_attempt += 1
    print("succes took ", n_attempt, " attempts")
    return doku
            
def attempt_full_circledoku(n):
    maxDigit = 2*n
    doku = np.zeros((n, maxDigit), dtype=np.int)
    for i in range(n):
        values = [] # a list of numbers to choose from
        for n in range(1, maxDigit+1):
            values.append(n)
        for j in range(maxDigit):
            value = values[np.random.randint(0, len(values))]             
            gen = [i, j, value]
            count = 1
            while not is_gen_valid(doku, gen):
                idx = np.random.randint(0, len(values))
                gen = [i, j, values[idx]]
                values.pop(idx)
                count += 1
                if len(values) == 0:
                    return False, doku
            doku[i, j] = gen[2]
    return True, doku

def is_gen_valid(doku, gen):
    # variable 'gen' is the digit the algorithm wants to genereate at certain position
    # its syntax is [x, y, digit]
    if is_gen_valid_for_ring(doku, gen) and is_gen_valid_for_slice(doku, gen) and is_gen_valid_for_wedge(doku, gen):
        return True
    else:
        return False
    
def is_gen_valid_for_ring(doku, gen):
    ring_content = doku[gen[0]][:]
    if gen[2] in ring_content:
        return False
    else:
        return True

def is_gen_valid_for_slice(doku, gen):
    n = len(doku)
    n_slice = gen[1] % n
    slice_content = doku.transpose()[n_slice::n][:]
    if gen[2] in slice_content:
        return False
    else:
        return True
    
def is_gen_valid_for_wedge(doku, gen):
    n = len(doku)
    n_wedge = int(gen[1] / 2)
    wedge_content = doku.transpose()[n_wedge*2:n_wedge*2+2][:]
    if gen[2] in wedge_content:
        return False
    else:
        return True

def construct_database():
    for n in [4,6,7,10]:
        k = 13 # amount of puzzles to generate per size/nRings
        for i in range(k):
            tic = time.clock()
            doku = gen_full_circledoku(n)
            toc = time.clock()
            print("Circledoku order:", n, ", nr: ", i, " took ", toc-tic, "seconds")
            filename_small = "CircleDoku_nrings" + str(n) + "_#" +str(i)
            np.savetxt(filename_small, doku, fmt='%i', delimiter=',', newline='\n' )        
        collect_smalls_to_big(n, k-1)
        
def collect_smalls_to_big(nRings, nPuzzles):
    filename_big = "CircleDokuDatabase_for_size_" + str(nRings)
    with open(filename_big, 'w'): pass # clear the file
    f=open(filename_big,'ab')
    for i in range(nPuzzles):
        filename_small = "CircleDoku_nrings"+str(nRings)+"_#"+str(i)
        doku = np.loadtxt(filename_small, delimiter=',')
        np.savetxt(f, doku, fmt='%i', delimiter=',', newline='\n' )
    f.close()

In [13]:
# in this cell you can see how generating database works

# the following call will create 50 circledokus for a few sizes (indicated in the function)
# it writes every sudoku to its own txt file
# when all is done it writes all to a bigger file that contains all puzzles of size nRings
# the advantage is that heavy calculation is only performed when the big txt file is closed
# when the calculation is broken off before 50, all the intermediate puzzles will still be saved
# in their respective small_txt file, and can be read out with a separate call to collect_smalls_to_big
# to a different big_txt file. The big_txt files can then be merged to complete the database
# note that with loading the database, the final big_txt file must have the correct name

# Generating circledoku's might take a while

# construct_database() 
# collect_smalls_to_big(4, 15) 

In [19]:
# this file read the big txt file to a 3d array, puzzles-rows-columns

def load_circleDoku_database(n):
    filename = "CircleDokuDatabase_for_size_"+str(n)
    a = load_database_file(filename)
    return a

def load_database_file(filename, n):
    a = np.loadtxt(filename, delimiter=',' )
    nDoku = int(len(a)/n)
    a = a.reshape(((nDoku, n, 2*n)))
    return a

def merge_database_files(n, file_in_1, file_in_2, file_out):
    a = load_database_file(file_in_1, n)
    b = load_database_file(file_in_2, n)
    a_len = len(a)
    b_len = len(b)
    c_len = a_len + b_len
    c = np.zeros((c_len, n, 2*n))
    c[:len(a)] = a
    c[len(a):] = b
    f=open(file_out,'ab')
    for i in range(c_len):
        doku = c[i]
        np.savetxt(f, doku, fmt='%i', delimiter=',', newline='\n' )
    f.close()

In [21]:
file_in_1 = "CircleDokuDatabase_for_size_4_22sept"
file_in_2 = "CircleDokuDatabase_for_size_4_23sept"
file_out = "CircleDokuDatabase_for_size_4_merged"
merge_database_files(4, file_in_1, file_in_2, file_out)